export const SET_BRIGHTNESS_VALUE = 'COLOR_EDIT/SET_BRIGHTNESS_VALUE'
export const SET_BLUR_VALUE = 'COLOR_EDIT/SET_BLUR_VALUE'
export const SET_SATURATION_VALUE = 'COLOR_EDIT/SET_SATURATION_VALUE'
export const SET_COLOR_CORRECTION_VALUES = 'COLOR_EDIT/SET_COLOR_CORRECTION_VALUES'
export const RESET_COLOR_CORRECTION = 'COLOR_EDIT/RESET_COLOR_CORRECTION'

export const SET_INITIAL_IMAGE = 'FILE_WORK/SET_INITIAL_IMAGE'
export const SET_MODIFIED_IMAGE = 'FILE_WORK/SET_MODIFIED_IMAGE'
export const SET_NEW_FILENAME = 'FILE_WORK/SET_NEW_FILENAME'
export const SET_IMAGE_PARAMS = 'FILE_WORK/SET_IMAGE_PARAMS'

export const SET_ACTIVE_PRESET = 'PRESETS/SET_ACTIVE_PRESET'
export const RESET_ACTIVE_PRESET = 'PRESETS/RESET_ACTIVE_PRESET'

export const SET_MEDIAN_FILTER_VALUE = 'MATH_FILTERS/SET_MEDIAN_FILTER_VALUE'
export const SET_BILATERAL_FILTER_VALUE = 'MATH_FILTERS/SET_BILATERAL_FILTER_VALUE'
export const SET_IS_FILTER_LOADING = 'MATH_FILTERS/SET_IS_FILTER_LOADING'
export const RESET_FILTER_VALUE = 'MATH_FILTERS/RESET_FILTER_VALUE'

export const SET_CROP_VALUES = 'CROP/SET_CROP_VALUES'
export const RESET_CROP_VALUES = 'CROP/RESET_CROP_VALUES'