export const SET_BRIGHTNESS_VALUE = 'COLOR_EDIT/SET_BRIGHTNESS_VALUE'
export const SET_BLUR_VALUE = 'COLOR_EDIT/SET_BLUR_VALUE'
export const SET_SATURATION_VALUE = 'COLOR_EDIT/SET_SATURATION_VALUE'
export const SET_COLOR_CORRECTION_VALUES = 'COLOR_EDIT/SET_COLOR_CORRECTION_VALUES'